/* 
 * configapi
 *
 * Config API lets you easily manage configuration at scale.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Configuration.Api;
using Cloudmersive.APIClient.NET.Configuration.Model;
using Cloudmersive.APIClient.NET.Configuration.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Configuration.Test
{
    /// <summary>
    ///  Class for testing CreateSettingRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CreateSettingRequestTests
    {
        // TODO uncomment below to declare an instance variable for CreateSettingRequest
        //private CreateSettingRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreateSettingRequest
            //instance = new CreateSettingRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreateSettingRequest
        /// </summary>
        [Test]
        public void CreateSettingRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreateSettingRequest
            //Assert.IsInstanceOfType<CreateSettingRequest> (instance, "variable 'instance' is a CreateSettingRequest");
        }


        /// <summary>
        /// Test the property 'BucketID'
        /// </summary>
        [Test]
        public void BucketIDTest()
        {
            // TODO unit test for the property 'BucketID'
        }
        /// <summary>
        /// Test the property 'BucketSecretKey'
        /// </summary>
        [Test]
        public void BucketSecretKeyTest()
        {
            // TODO unit test for the property 'BucketSecretKey'
        }
        /// <summary>
        /// Test the property 'SettingName'
        /// </summary>
        [Test]
        public void SettingNameTest()
        {
            // TODO unit test for the property 'SettingName'
        }
        /// <summary>
        /// Test the property 'SettingType'
        /// </summary>
        [Test]
        public void SettingTypeTest()
        {
            // TODO unit test for the property 'SettingType'
        }
        /// <summary>
        /// Test the property 'SettingValue'
        /// </summary>
        [Test]
        public void SettingValueTest()
        {
            // TODO unit test for the property 'SettingValue'
        }
        /// <summary>
        /// Test the property 'SettingDescription'
        /// </summary>
        [Test]
        public void SettingDescriptionTest()
        {
            // TODO unit test for the property 'SettingDescription'
        }
        /// <summary>
        /// Test the property 'SettingTags'
        /// </summary>
        [Test]
        public void SettingTagsTest()
        {
            // TODO unit test for the property 'SettingTags'
        }

    }

}
