/* 
 * configapi
 *
 * Config API lets you easily manage configuration at scale.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Configuration.Api;
using Cloudmersive.APIClient.NET.Configuration.Model;
using Cloudmersive.APIClient.NET.Configuration.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Configuration.Test
{
    /// <summary>
    ///  Class for testing CreateSettingResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CreateSettingResponseTests
    {
        // TODO uncomment below to declare an instance variable for CreateSettingResponse
        //private CreateSettingResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreateSettingResponse
            //instance = new CreateSettingResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreateSettingResponse
        /// </summary>
        [Test]
        public void CreateSettingResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreateSettingResponse
            //Assert.IsInstanceOfType<CreateSettingResponse> (instance, "variable 'instance' is a CreateSettingResponse");
        }


        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Test]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }
        /// <summary>
        /// Test the property 'SettingDefinitionID'
        /// </summary>
        [Test]
        public void SettingDefinitionIDTest()
        {
            // TODO unit test for the property 'SettingDefinitionID'
        }
        /// <summary>
        /// Test the property 'SettingValueID'
        /// </summary>
        [Test]
        public void SettingValueIDTest()
        {
            // TODO unit test for the property 'SettingValueID'
        }

    }

}
