/* 
 * configapi
 *
 * Config API lets you easily manage configuration at scale.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Configuration.Api;
using Cloudmersive.APIClient.NET.Configuration.Model;
using Cloudmersive.APIClient.NET.Configuration.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Configuration.Test
{
    /// <summary>
    ///  Class for testing HttpWwwFormUrlEncodedParameter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class HttpWwwFormUrlEncodedParameterTests
    {
        // TODO uncomment below to declare an instance variable for HttpWwwFormUrlEncodedParameter
        //private HttpWwwFormUrlEncodedParameter instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of HttpWwwFormUrlEncodedParameter
            //instance = new HttpWwwFormUrlEncodedParameter();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HttpWwwFormUrlEncodedParameter
        /// </summary>
        [Test]
        public void HttpWwwFormUrlEncodedParameterInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HttpWwwFormUrlEncodedParameter
            //Assert.IsInstanceOfType<HttpWwwFormUrlEncodedParameter> (instance, "variable 'instance' is a HttpWwwFormUrlEncodedParameter");
        }


        /// <summary>
        /// Test the property 'KeyName'
        /// </summary>
        [Test]
        public void KeyNameTest()
        {
            // TODO unit test for the property 'KeyName'
        }
        /// <summary>
        /// Test the property 'KeyValue'
        /// </summary>
        [Test]
        public void KeyValueTest()
        {
            // TODO unit test for the property 'KeyValue'
        }
        /// <summary>
        /// Test the property 'UseOutputFromPreviousTask'
        /// </summary>
        [Test]
        public void UseOutputFromPreviousTaskTest()
        {
            // TODO unit test for the property 'UseOutputFromPreviousTask'
        }

    }

}
