/* 
 * configapi
 *
 * Config API lets you easily manage configuration at scale.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Configuration.Api;
using Cloudmersive.APIClient.NET.Configuration.Model;
using Cloudmersive.APIClient.NET.Configuration.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Configuration.Test
{
    /// <summary>
    ///  Class for testing HttpOrchestrationRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class HttpOrchestrationRequestTests
    {
        // TODO uncomment below to declare an instance variable for HttpOrchestrationRequest
        //private HttpOrchestrationRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of HttpOrchestrationRequest
            //instance = new HttpOrchestrationRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HttpOrchestrationRequest
        /// </summary>
        [Test]
        public void HttpOrchestrationRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HttpOrchestrationRequest
            //Assert.IsInstanceOfType<HttpOrchestrationRequest> (instance, "variable 'instance' is a HttpOrchestrationRequest");
        }


        /// <summary>
        /// Test the property 'HttpTasks'
        /// </summary>
        [Test]
        public void HttpTasksTest()
        {
            // TODO unit test for the property 'HttpTasks'
        }

    }

}
