/* 
 * configapi
 *
 * Config API lets you easily manage configuration at scale.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Configuration.Api;
using Cloudmersive.APIClient.NET.Configuration.Model;
using Cloudmersive.APIClient.NET.Configuration.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Configuration.Test
{
    /// <summary>
    ///  Class for testing HttpGetParameter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class HttpGetParameterTests
    {
        // TODO uncomment below to declare an instance variable for HttpGetParameter
        //private HttpGetParameter instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of HttpGetParameter
            //instance = new HttpGetParameter();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HttpGetParameter
        /// </summary>
        [Test]
        public void HttpGetParameterInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HttpGetParameter
            //Assert.IsInstanceOfType<HttpGetParameter> (instance, "variable 'instance' is a HttpGetParameter");
        }


        /// <summary>
        /// Test the property 'ParameterName'
        /// </summary>
        [Test]
        public void ParameterNameTest()
        {
            // TODO unit test for the property 'ParameterName'
        }
        /// <summary>
        /// Test the property 'ParameterValue'
        /// </summary>
        [Test]
        public void ParameterValueTest()
        {
            // TODO unit test for the property 'ParameterValue'
        }
        /// <summary>
        /// Test the property 'UseOutputFromPreviousTask'
        /// </summary>
        [Test]
        public void UseOutputFromPreviousTaskTest()
        {
            // TODO unit test for the property 'UseOutputFromPreviousTask'
        }

    }

}
