/* 
 * configapi
 *
 * Config API lets you easily manage configuration at scale.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Configuration.Api;
using Cloudmersive.APIClient.NET.Configuration.Model;
using Cloudmersive.APIClient.NET.Configuration.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Configuration.Test
{
    /// <summary>
    ///  Class for testing HttpOrchestrationResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class HttpOrchestrationResponseTests
    {
        // TODO uncomment below to declare an instance variable for HttpOrchestrationResponse
        //private HttpOrchestrationResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of HttpOrchestrationResponse
            //instance = new HttpOrchestrationResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HttpOrchestrationResponse
        /// </summary>
        [Test]
        public void HttpOrchestrationResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HttpOrchestrationResponse
            //Assert.IsInstanceOfType<HttpOrchestrationResponse> (instance, "variable 'instance' is a HttpOrchestrationResponse");
        }


        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Test]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }
        /// <summary>
        /// Test the property 'TasksCompleted'
        /// </summary>
        [Test]
        public void TasksCompletedTest()
        {
            // TODO unit test for the property 'TasksCompleted'
        }
        /// <summary>
        /// Test the property 'OutputStringType'
        /// </summary>
        [Test]
        public void OutputStringTypeTest()
        {
            // TODO unit test for the property 'OutputStringType'
        }
        /// <summary>
        /// Test the property 'OutputBinaryType'
        /// </summary>
        [Test]
        public void OutputBinaryTypeTest()
        {
            // TODO unit test for the property 'OutputBinaryType'
        }

    }

}
