/* 
 * configapi
 *
 * Config API lets you easily manage configuration at scale.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Configuration.Api;
using Cloudmersive.APIClient.NET.Configuration.Model;
using Cloudmersive.APIClient.NET.Configuration.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Configuration.Test
{
    /// <summary>
    ///  Class for testing HttpOrchestrationTask
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class HttpOrchestrationTaskTests
    {
        // TODO uncomment below to declare an instance variable for HttpOrchestrationTask
        //private HttpOrchestrationTask instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of HttpOrchestrationTask
            //instance = new HttpOrchestrationTask();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HttpOrchestrationTask
        /// </summary>
        [Test]
        public void HttpOrchestrationTaskInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HttpOrchestrationTask
            //Assert.IsInstanceOfType<HttpOrchestrationTask> (instance, "variable 'instance' is a HttpOrchestrationTask");
        }


        /// <summary>
        /// Test the property 'TaskName'
        /// </summary>
        [Test]
        public void TaskNameTest()
        {
            // TODO unit test for the property 'TaskName'
        }
        /// <summary>
        /// Test the property 'HttpMethod'
        /// </summary>
        [Test]
        public void HttpMethodTest()
        {
            // TODO unit test for the property 'HttpMethod'
        }
        /// <summary>
        /// Test the property 'URL'
        /// </summary>
        [Test]
        public void URLTest()
        {
            // TODO unit test for the property 'URL'
        }
        /// <summary>
        /// Test the property 'HttpHeaders'
        /// </summary>
        [Test]
        public void HttpHeadersTest()
        {
            // TODO unit test for the property 'HttpHeaders'
        }
        /// <summary>
        /// Test the property 'QueryParameters'
        /// </summary>
        [Test]
        public void QueryParametersTest()
        {
            // TODO unit test for the property 'QueryParameters'
        }
        /// <summary>
        /// Test the property 'FormDataParameters'
        /// </summary>
        [Test]
        public void FormDataParametersTest()
        {
            // TODO unit test for the property 'FormDataParameters'
        }
        /// <summary>
        /// Test the property 'WwwFormUrlEncodedParameters'
        /// </summary>
        [Test]
        public void WwwFormUrlEncodedParametersTest()
        {
            // TODO unit test for the property 'WwwFormUrlEncodedParameters'
        }
        /// <summary>
        /// Test the property 'RawTextBody'
        /// </summary>
        [Test]
        public void RawTextBodyTest()
        {
            // TODO unit test for the property 'RawTextBody'
        }
        /// <summary>
        /// Test the property 'RawBinaryBody'
        /// </summary>
        [Test]
        public void RawBinaryBodyTest()
        {
            // TODO unit test for the property 'RawBinaryBody'
        }

    }

}
