/* 
 * configapi
 *
 * Config API lets you easily manage configuration at scale.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Configuration.Api;
using Cloudmersive.APIClient.NET.Configuration.Model;
using Cloudmersive.APIClient.NET.Configuration.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Configuration.Test
{
    /// <summary>
    ///  Class for testing SettingValue
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SettingValueTests
    {
        // TODO uncomment below to declare an instance variable for SettingValue
        //private SettingValue instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SettingValue
            //instance = new SettingValue();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SettingValue
        /// </summary>
        [Test]
        public void SettingValueInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SettingValue
            //Assert.IsInstanceOfType<SettingValue> (instance, "variable 'instance' is a SettingValue");
        }


        /// <summary>
        /// Test the property 'ConfigSettingValueID'
        /// </summary>
        [Test]
        public void ConfigSettingValueIDTest()
        {
            // TODO unit test for the property 'ConfigSettingValueID'
        }
        /// <summary>
        /// Test the property 'ConfigSettingDefinitionID'
        /// </summary>
        [Test]
        public void ConfigSettingDefinitionIDTest()
        {
            // TODO unit test for the property 'ConfigSettingDefinitionID'
        }
        /// <summary>
        /// Test the property 'ConfigSettingValue'
        /// </summary>
        [Test]
        public void ConfigSettingValueTest()
        {
            // TODO unit test for the property 'ConfigSettingValue'
        }
        /// <summary>
        /// Test the property 'ConfigSettingLastModified'
        /// </summary>
        [Test]
        public void ConfigSettingLastModifiedTest()
        {
            // TODO unit test for the property 'ConfigSettingLastModified'
        }

    }

}
