/* 
 * configapi
 *
 * Config API lets you easily manage configuration at scale.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Configuration.Api;
using Cloudmersive.APIClient.NET.Configuration.Model;
using Cloudmersive.APIClient.NET.Configuration.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Configuration.Test
{
    /// <summary>
    ///  Class for testing TaskOutputReference
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TaskOutputReferenceTests
    {
        // TODO uncomment below to declare an instance variable for TaskOutputReference
        //private TaskOutputReference instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TaskOutputReference
            //instance = new TaskOutputReference();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TaskOutputReference
        /// </summary>
        [Test]
        public void TaskOutputReferenceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TaskOutputReference
            //Assert.IsInstanceOfType<TaskOutputReference> (instance, "variable 'instance' is a TaskOutputReference");
        }


        /// <summary>
        /// Test the property 'TaskName'
        /// </summary>
        [Test]
        public void TaskNameTest()
        {
            // TODO unit test for the property 'TaskName'
        }
        /// <summary>
        /// Test the property 'TargetType'
        /// </summary>
        [Test]
        public void TargetTypeTest()
        {
            // TODO unit test for the property 'TargetType'
        }

    }

}
