/* 
 * configapi
 *
 * Config API lets you easily manage configuration at scale.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Configuration.Api;
using Cloudmersive.APIClient.NET.Configuration.Model;
using Cloudmersive.APIClient.NET.Configuration.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Configuration.Test
{
    /// <summary>
    ///  Class for testing UpdateSettingRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UpdateSettingRequestTests
    {
        // TODO uncomment below to declare an instance variable for UpdateSettingRequest
        //private UpdateSettingRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UpdateSettingRequest
            //instance = new UpdateSettingRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UpdateSettingRequest
        /// </summary>
        [Test]
        public void UpdateSettingRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UpdateSettingRequest
            //Assert.IsInstanceOfType<UpdateSettingRequest> (instance, "variable 'instance' is a UpdateSettingRequest");
        }


        /// <summary>
        /// Test the property 'BucketID'
        /// </summary>
        [Test]
        public void BucketIDTest()
        {
            // TODO unit test for the property 'BucketID'
        }
        /// <summary>
        /// Test the property 'BucketSecretKey'
        /// </summary>
        [Test]
        public void BucketSecretKeyTest()
        {
            // TODO unit test for the property 'BucketSecretKey'
        }
        /// <summary>
        /// Test the property 'SettingToUpdate'
        /// </summary>
        [Test]
        public void SettingToUpdateTest()
        {
            // TODO unit test for the property 'SettingToUpdate'
        }

    }

}
