/* 
 * configapi
 *
 * Config API lets you easily manage configuration at scale.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Cloudmersive.APIClient.NET.Configuration.Client;
using Cloudmersive.APIClient.NET.Configuration.Api;
using Cloudmersive.APIClient.NET.Configuration.Model;

namespace Cloudmersive.APIClient.NET.Configuration.Test
{
    /// <summary>
    ///  Class for testing OrchestratorApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class OrchestratorApiTests
    {
        private OrchestratorApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new OrchestratorApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OrchestratorApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' OrchestratorApi
            //Assert.IsInstanceOfType(typeof(OrchestratorApi), instance, "instance is a OrchestratorApi");
        }

        
        /// <summary>
        /// Test OrchestratorHttpSimple
        /// </summary>
        [Test]
        public void OrchestratorHttpSimpleTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //HttpOrchestrationRequest request = null;
            //var response = instance.OrchestratorHttpSimple(request);
            //Assert.IsInstanceOf<HttpOrchestrationResponse> (response, "response is HttpOrchestrationResponse");
        }
        
    }

}
