/* 
 * configapi
 *
 * Config API lets you easily manage configuration at scale.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Cloudmersive.APIClient.NET.Configuration.Client;
using Cloudmersive.APIClient.NET.Configuration.Api;
using Cloudmersive.APIClient.NET.Configuration.Model;

namespace Cloudmersive.APIClient.NET.Configuration.Test
{
    /// <summary>
    ///  Class for testing SettingsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class SettingsApiTests
    {
        private SettingsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new SettingsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SettingsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' SettingsApi
            //Assert.IsInstanceOfType(typeof(SettingsApi), instance, "instance is a SettingsApi");
        }

        
        /// <summary>
        /// Test SettingsCreateSetting
        /// </summary>
        [Test]
        public void SettingsCreateSettingTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateSettingRequest request = null;
            //var response = instance.SettingsCreateSetting(request);
            //Assert.IsInstanceOf<CreateSettingResponse> (response, "response is CreateSettingResponse");
        }
        
        /// <summary>
        /// Test SettingsListSettings
        /// </summary>
        [Test]
        public void SettingsListSettingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ListSettingsRequest request = null;
            //var response = instance.SettingsListSettings(request);
            //Assert.IsInstanceOf<ListSettingsResponse> (response, "response is ListSettingsResponse");
        }
        
    }

}
