/* 
 * configapi
 *
 * Config API lets you easily manage configuration at scale.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Cloudmersive.APIClient.NET.Configuration.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NET.Configuration.Model
{
    /// <summary>
    /// Defines a parameter of type FormData (multipart/form-data)
    /// </summary>
    [DataContract]
    public partial class HttpFormDataParameter :  IEquatable<HttpFormDataParameter>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HttpFormDataParameter" /> class.
        /// </summary>
        /// <param name="parameterName">Name of the parameter.</param>
        /// <param name="parameterTextValue">Text value of the parameter; if set, do not set ParameterFileContents or UseOutputFromPreviousTask.</param>
        /// <param name="parameterFileContents">Binary contents of the parameter; if set, do not set ParameterTextValue or UseOutputFromPreviousTask.</param>
        /// <param name="useOutputFromPreviousTask">Optional; use the output from a previous task as the input to this parameter.  Set to null (default) to ignore..</param>
        public HttpFormDataParameter(string parameterName = default(string), string parameterTextValue = default(string), byte[] parameterFileContents = default(byte[]), TaskOutputReference useOutputFromPreviousTask = default(TaskOutputReference))
        {
            this.ParameterName = parameterName;
            this.ParameterTextValue = parameterTextValue;
            this.ParameterFileContents = parameterFileContents;
            this.UseOutputFromPreviousTask = useOutputFromPreviousTask;
        }
        
        /// <summary>
        /// Name of the parameter
        /// </summary>
        /// <value>Name of the parameter</value>
        [DataMember(Name="ParameterName", EmitDefaultValue=false)]
        public string ParameterName { get; set; }

        /// <summary>
        /// Text value of the parameter; if set, do not set ParameterFileContents or UseOutputFromPreviousTask
        /// </summary>
        /// <value>Text value of the parameter; if set, do not set ParameterFileContents or UseOutputFromPreviousTask</value>
        [DataMember(Name="ParameterTextValue", EmitDefaultValue=false)]
        public string ParameterTextValue { get; set; }

        /// <summary>
        /// Binary contents of the parameter; if set, do not set ParameterTextValue or UseOutputFromPreviousTask
        /// </summary>
        /// <value>Binary contents of the parameter; if set, do not set ParameterTextValue or UseOutputFromPreviousTask</value>
        [DataMember(Name="ParameterFileContents", EmitDefaultValue=false)]
        public byte[] ParameterFileContents { get; set; }

        /// <summary>
        /// Optional; use the output from a previous task as the input to this parameter.  Set to null (default) to ignore.
        /// </summary>
        /// <value>Optional; use the output from a previous task as the input to this parameter.  Set to null (default) to ignore.</value>
        [DataMember(Name="UseOutputFromPreviousTask", EmitDefaultValue=false)]
        public TaskOutputReference UseOutputFromPreviousTask { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class HttpFormDataParameter {\n");
            sb.Append("  ParameterName: ").Append(ParameterName).Append("\n");
            sb.Append("  ParameterTextValue: ").Append(ParameterTextValue).Append("\n");
            sb.Append("  ParameterFileContents: ").Append(ParameterFileContents).Append("\n");
            sb.Append("  UseOutputFromPreviousTask: ").Append(UseOutputFromPreviousTask).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as HttpFormDataParameter);
        }

        /// <summary>
        /// Returns true if HttpFormDataParameter instances are equal
        /// </summary>
        /// <param name="input">Instance of HttpFormDataParameter to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(HttpFormDataParameter input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ParameterName == input.ParameterName ||
                    (this.ParameterName != null &&
                    this.ParameterName.Equals(input.ParameterName))
                ) && 
                (
                    this.ParameterTextValue == input.ParameterTextValue ||
                    (this.ParameterTextValue != null &&
                    this.ParameterTextValue.Equals(input.ParameterTextValue))
                ) && 
                (
                    this.ParameterFileContents == input.ParameterFileContents ||
                    (this.ParameterFileContents != null &&
                    this.ParameterFileContents.Equals(input.ParameterFileContents))
                ) && 
                (
                    this.UseOutputFromPreviousTask == input.UseOutputFromPreviousTask ||
                    (this.UseOutputFromPreviousTask != null &&
                    this.UseOutputFromPreviousTask.Equals(input.UseOutputFromPreviousTask))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ParameterName != null)
                    hashCode = hashCode * 59 + this.ParameterName.GetHashCode();
                if (this.ParameterTextValue != null)
                    hashCode = hashCode * 59 + this.ParameterTextValue.GetHashCode();
                if (this.ParameterFileContents != null)
                    hashCode = hashCode * 59 + this.ParameterFileContents.GetHashCode();
                if (this.UseOutputFromPreviousTask != null)
                    hashCode = hashCode * 59 + this.UseOutputFromPreviousTask.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
