/* 
 * configapi
 *
 * Config API lets you easily manage configuration at scale.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Cloudmersive.APIClient.NET.Configuration.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NET.Configuration.Model
{
    /// <summary>
    /// HTTP Orchestration request
    /// </summary>
    [DataContract]
    public partial class HttpOrchestrationRequest :  IEquatable<HttpOrchestrationRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HttpOrchestrationRequest" /> class.
        /// </summary>
        /// <param name="httpTasks">Tasks to perform, in the order you wish to perform them.</param>
        public HttpOrchestrationRequest(List<HttpOrchestrationTask> httpTasks = default(List<HttpOrchestrationTask>))
        {
            this.HttpTasks = httpTasks;
        }
        
        /// <summary>
        /// Tasks to perform, in the order you wish to perform them
        /// </summary>
        /// <value>Tasks to perform, in the order you wish to perform them</value>
        [DataMember(Name="HttpTasks", EmitDefaultValue=false)]
        public List<HttpOrchestrationTask> HttpTasks { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class HttpOrchestrationRequest {\n");
            sb.Append("  HttpTasks: ").Append(HttpTasks).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as HttpOrchestrationRequest);
        }

        /// <summary>
        /// Returns true if HttpOrchestrationRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of HttpOrchestrationRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(HttpOrchestrationRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.HttpTasks == input.HttpTasks ||
                    this.HttpTasks != null &&
                    this.HttpTasks.SequenceEqual(input.HttpTasks)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.HttpTasks != null)
                    hashCode = hashCode * 59 + this.HttpTasks.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
