/* 
 * configapi
 *
 * Config API lets you easily manage configuration at scale.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Cloudmersive.APIClient.NET.Configuration.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NET.Configuration.Model
{
    /// <summary>
    /// UpdateSettingRequest
    /// </summary>
    [DataContract]
    public partial class UpdateSettingRequest :  IEquatable<UpdateSettingRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateSettingRequest" /> class.
        /// </summary>
        /// <param name="bucketID">bucketID.</param>
        /// <param name="bucketSecretKey">bucketSecretKey.</param>
        /// <param name="settingToUpdate">settingToUpdate.</param>
        public UpdateSettingRequest(string bucketID = default(string), string bucketSecretKey = default(string), SettingValue settingToUpdate = default(SettingValue))
        {
            this.BucketID = bucketID;
            this.BucketSecretKey = bucketSecretKey;
            this.SettingToUpdate = settingToUpdate;
        }
        
        /// <summary>
        /// Gets or Sets BucketID
        /// </summary>
        [DataMember(Name="BucketID", EmitDefaultValue=false)]
        public string BucketID { get; set; }

        /// <summary>
        /// Gets or Sets BucketSecretKey
        /// </summary>
        [DataMember(Name="BucketSecretKey", EmitDefaultValue=false)]
        public string BucketSecretKey { get; set; }

        /// <summary>
        /// Gets or Sets SettingToUpdate
        /// </summary>
        [DataMember(Name="SettingToUpdate", EmitDefaultValue=false)]
        public SettingValue SettingToUpdate { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UpdateSettingRequest {\n");
            sb.Append("  BucketID: ").Append(BucketID).Append("\n");
            sb.Append("  BucketSecretKey: ").Append(BucketSecretKey).Append("\n");
            sb.Append("  SettingToUpdate: ").Append(SettingToUpdate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UpdateSettingRequest);
        }

        /// <summary>
        /// Returns true if UpdateSettingRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of UpdateSettingRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpdateSettingRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.BucketID == input.BucketID ||
                    (this.BucketID != null &&
                    this.BucketID.Equals(input.BucketID))
                ) && 
                (
                    this.BucketSecretKey == input.BucketSecretKey ||
                    (this.BucketSecretKey != null &&
                    this.BucketSecretKey.Equals(input.BucketSecretKey))
                ) && 
                (
                    this.SettingToUpdate == input.SettingToUpdate ||
                    (this.SettingToUpdate != null &&
                    this.SettingToUpdate.Equals(input.SettingToUpdate))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.BucketID != null)
                    hashCode = hashCode * 59 + this.BucketID.GetHashCode();
                if (this.BucketSecretKey != null)
                    hashCode = hashCode * 59 + this.BucketSecretKey.GetHashCode();
                if (this.SettingToUpdate != null)
                    hashCode = hashCode * 59 + this.SettingToUpdate.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
